"""add images field

Revision ID: 329178604802
Revises: 95f8a99b4618
Create Date: 2025-07-21 19:57:47.550203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329178604802'
down_revision = '95f8a99b4618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
